on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: atomdevacr.azurecr.io
        username: ${{ secrets.acr_atomdevacr_username }}
        password: ${{ secrets.acr_atomdevacr_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t atomdevacr.azurecr.io/atomdev:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push atomdevacr.azurecr.io/atomdev:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_atomdev_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep user-interface-dev | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace user-interface-dev`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: user-interface-dev
        container-registry-url: atomdevacr.azurecr.io
        container-registry-username: ${{ secrets.acr_atomdevacr_username }}
        container-registry-password: ${{ secrets.acr_atomdevacr_password }}
        secret-name: atomdevdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: user-interface-dev
        manifests: |
          manifests/deployment-atomdev.yml
          manifests/service-atomdev.yml
        images: |
          atomdevacr.azurecr.io/atomdev:${{ github.sha }}
        imagepullsecrets: |
          atomdevdockerauth
