on:
  push:
    branches:
      - prod

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: atomconstructacr.azurecr.io
        username: ${{ secrets.acr_atomconstructacr_username }}
        password: ${{ secrets.acr_atomconstructacr_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t atomconstructacr.azurecr.io/atom:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push atomconstructacr.azurecr.io/atom:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_atom_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep user-interface | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace user-interface`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: user-interface
        container-registry-url: atomconstructacr.azurecr.io
        container-registry-username: ${{ secrets.acr_atomconstructacr_username }}
        container-registry-password: ${{ secrets.acr_atomconstructacr_password }}
        secret-name: atomdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: user-interface
        manifests: |
          manifests/deployment-atom.yml
          manifests/service-atom.yml
        images: |
          atomconstructacr.azurecr.io/atom:${{ github.sha }}
        imagepullsecrets: |
          atomdockerauth
